---
title: "State-space assessment project notes"
date: "10/02/2018"
output: html_document
---

###10/2
Project started. This notebook tracks progress and decisions made.

###10/10
Herring run 13 model is up and running. There was a problem with trying to run it without all of the data files that was causing R to crash. My solution was to generate some default data files and go from there. Might be an operating system issue but seems easy enough to bypass for now.

I did some quick simulation self-tests using the SAM "simulate" feature which allows you to simulate from a fitted sam model (see end of herring_run13.R).

###10/17
Been working on coding up the SAM model in R so we can then recreate the self-tests of the simulate feature. To get started I'm using the Atl herring run 13 fit as the parameter set of the simulation. You can check out the code here: https://github.com/perretti/state-space-tests/tree/master/simulation. 

My goal right now is to verify I have the model equations right by recreating the fit time series exactly. So far I've be able to recreate the N-at-age fit time series by back-calculating the fit process errors and simulating forward from the fit initial conditions. And I've been able to do the same for total catch. Now I'm working on recreating the survey fits.

###10/24
Finished coding the deterministic SAM equations and checked them against the SAM fit output. The two lines are identical so I'm convinced I have the deterministic component of the model correct.

Simulations results in large swings in abundance. The reason the simulate.sam() feature gives such well-constrained simulations is it simulates, "conditional on estimated values of F and N, rather than also simulating F and N forward from their initial values". In other words, it doesn't simulate N or F, but rather just uses the fit values.

In order to generate a simulation that actually simulates N and F you have to call sam.fit with sim.condRE = FALSE, and then pass that fit to simulate.sam().

Now, if you try to fit a sam model to these simulations, about half the time it crashes with a gradient error. I think that's because it can't fit to the wild swings implied by the fit.

Here is my best guess for what's going on with the wild swings--

https://github.com/perretti/state-space-tests/blob/master/random_walk_case_study/random_walk.R

Estimates on the natural scale are skewed toward higher values due to the log-transformation.

Plan is to run some self-tests next.